USE [HRDB]

-- 1
INSERT INTO [EMPLOYEES] 
(
    EMPLOYEE_ID, 
    FIRST_NAME, 
    LAST_NAME, 
    EMAIL, 
    PHONE_NUMBER, 
    HIRE_DATE, 
    JOB_ID, 
    SALARY, 
    COMMISSION_PCT, 
    MANAGER_ID, 
    DEPARTMENT_ID)
SELECT TOP 1 * FROM 
(
    SELECT MAX(e.EMPLOYEE_ID) + 1 AS EMPLOYEE_ID,
    'Anton' AS FIRST_NAME,
    'Pashkouski' AS LAST_NAME,
    'email@email' AS EMAIL,
    '123123' AS PHONE_NUMBER,
    GETDATE() AS HIRE_DATE,
    'PU_CLERK' AS JOB_ID,
    (SELECT MIN(e.SALARY) FROM EMPLOYEES e WHERE e.SALARY IS NOT NULL AND e.JOB_ID = 'PU_CLERK') AS SALARY,
    NULL AS COMMISION_PCT,
    NULL AS MANAGER_ID,
    NULL AS DEPARTAMENT_ID
    FROM EMPLOYEES e
) st 

-- 2
INSERT INTO [JOB_HISTORY]
(
    [EMPLOYEE_ID], 
    [START_DATE], 
    [END_DATE], 
    [JOB_ID], 
    [DEPARTMENT_ID])
SELECT * FROM 
(
    SELECT 
        e.EMPLOYEE_ID,
        e.HIRE_DATE,
        GETDATE() AS END_DATE,
        e.JOB_ID,
        e.DEPARTMENT_ID
    FROM EMPLOYEES e
    INNER JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
    WHERE (d.DEPARTMENT_NAME = 'IT' AND d.MANAGER_ID != e.EMPLOYEE_ID) OR
          (d.DEPARTMENT_NAME = 'Shipping' AND e.JOB_ID = 'SH_CLERK' AND DATEDIFF(DAY, e.HIRE_DATE, GETDATE()) <= 7)
) st

-- 3
UPDATE [EMPLOYEES]
SET
    EMAIL = CONCAT(LEFT([LAST_NAME], 1), [FIRST_NAME], [DEPARTMENT_ID])
WHERE [DEPARTMENT_ID]  = (
    SELECT TOP 1 
        e.[DEPARTMENT_ID] 
    FROM [EMPLOYEES] e
    GROUP BY e.[DEPARTMENT_ID]
    ORDER BY COUNT(*) DESC
)

-- 4
UPDATE [EMPLOYEES]
SET
    COMMISSION_PCT = CASE WHEN COMMISSION_PCT IS NULL THEN 0.1 ELSE COMMISSION_PCT + 0.1 END
WHERE [EMPLOYEE_ID] IN
(
    SELECT 
        e.EMPLOYEE_ID
    FROM EMPLOYEES e
    INNER JOIN 
    (
    SELECT
        e.[JOB_ID],
        MAX(e.SALARY) AS MAX_SALARY 
    FROM EMPLOYEES e 
    GROUP BY e.[JOB_ID]
    ) st ON st.JOB_ID = e.JOB_ID AND st.MAX_SALARY = e.SALARY
)

-- 5
UPDATE [EMPLOYEES]
SET
    JOB_ID = 'AD_VP'
WHERE [EMPLOYEE_ID] = (
    SELECT
        e.EMPLOYEE_ID 
    FROM EMPLOYEES e
    INNER JOIN DEPARTMENTS d ON 
        e.DEPARTMENT_ID = d.DEPARTMENT_ID AND 
        e.EMPLOYEE_ID = d.MANAGER_ID AND 
        d.DEPARTMENT_NAME = 'IT'
)
 
INSERT INTO [JOB_HISTORY]
(
    [EMPLOYEE_ID], 
    [START_DATE], 
    [END_DATE], 
    [JOB_ID], 
    [DEPARTMENT_ID])
SELECT TOP 1 * FROM
(
    SELECT
        e.EMPLOYEE_ID,
        GETDATE() AS [START_DATE],
        NULL AS END_DATE,
        e.JOB_ID,
        e.DEPARTMENT_ID
    FROM EMPLOYEES e
    INNER JOIN DEPARTMENTS d ON 
        e.DEPARTMENT_ID = d.DEPARTMENT_ID AND 
        e.EMPLOYEE_ID = d.MANAGER_ID AND 
        d.DEPARTMENT_NAME = 'IT'
) st

-- 6
DELETE FROM [JOBS]
WHERE JOB_ID NOT IN (
    SELECT DISTINCT 
        e.JOB_ID
    FROM EMPLOYEES e
    WHERE e.JOB_ID IS NOT NULL

    UNION 

    SELECT DISTINCT
        jh.JOB_ID
    FROM JOB_HISTORY jh
    WHERE jh.JOB_ID IS NOT NULL
)

-- 7
DELETE FROM [JOB_HISTORY]
WHERE EMPLOYEE_ID NOT IN (
    SELECT DISTINCT e.MANAGER_ID 
    FROM EMPLOYEES e 
    WHERE e.MANAGER_ID IS NOT NULL

    UNION 

    SELECT DISTINCT 
        d.MANAGER_ID
    FROM DEPARTMENTS d
    WHERE d.MANAGER_ID IS NOT NULL
)

DELETE FROM [EMPLOYEES]
WHERE EMPLOYEE_ID NOT IN (
    SELECT DISTINCT e.MANAGER_ID 
    FROM EMPLOYEES e 
    WHERE e.MANAGER_ID IS NOT NULL

    UNION 

    SELECT DISTINCT 
        d.MANAGER_ID
    FROM DEPARTMENTS d
    WHERE d.MANAGER_ID IS NOT NULL
)